### ISSUE TITLE
ErrStr:no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by pedro-abundio-wang** [apache/mxnet#16527]
Environment Info:

I have install CUDA 10.0, and use mxnet-numpy download from offical support http://numpy.mxnet.io

Runing the following code ,then i got the error info :

`
x = np.ones((2, 3), ctx=npx.gpu())
x
`

`MXNetError: [11:41:41] src/operator/contrib/./.././../common/../operator/mxnet_op.h:794: Check failed: err == cudaSuccess (48 vs. 0) : Name: mxnet_generic_kernel ErrStr:no kernel image is available for execution on the device
Stack trace:
  [bt] (0) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x52f66b) [0x7f023876466b]
  [bt] (1) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x32ca2fc) [0x7f023b4ff2fc]
  [bt] (2) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x3bb1d64) [0x7f023bde6d64]
  [bt] (3) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::imperative::PushFCompute(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const+0x307) [0x7f023aa1f067]
  [bt] (4) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2735e14) [0x7f023a96ae14]
  [bt] (5) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x27437a9) [0x7f023a9787a9]
  [bt] (6) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2746c10) [0x7f023a97bc10]
  [bt] (7) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2746ea6) [0x7f023a97bea6]
  [bt] (8) /home/pedro/miniconda3/envs/d2l-numpy/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2741fb4) [0x7f023a976fb4]`

**Comment by ptrendx** [comment]
What is the GPU you are using?

**Comment by pedro-abundio-wang** [comment]
I am working on my laptop using GeForce GT 750M

**Comment by pedro-abundio-wang** [comment]
Any suggestion?

**Comment by ptrendx** [comment]
Hmmm, that is strange - GT 750M has compute capability 3.0, which is in the list of known CUDA_ARCHs in the Makefile:
https://github.com/apache/incubator-mxnet/blob/master/Makefile#L434
Maybe the pip package does not include all of them?

@pedro-abundio-wang Could you try building MXNet from source?

**Comment by pedro-abundio-wang** [comment]
OK I can try this.
One more question? Where can i find official reference to rebuild mxnet source code and use numpy interface?

**Comment by pedro-abundio-wang** [comment]
> 
> 
> Hmmm, that is strange - GT 750M has compute capability 3.0, which is in the list of known CUDA_ARCHs in the Makefile:
> https://github.com/apache/incubator-mxnet/blob/master/Makefile#L434
> Maybe the pip package does not include all of them?
> 
> @pedro-abundio-wang Could you try building MXNet from source?

**Comment by pedro-abundio-wang** [comment]
![image](https://user-images.githubusercontent.com/50159788/68206065-c7327d00-0006-11ea-81a0-d88451f4659b.png)

![image](https://user-images.githubusercontent.com/50159788/68206198-14aeea00-0007-11ea-9e19-878dd1a51918.png)


![image](https://user-images.githubusercontent.com/50159788/68206129-e4674b80-0006-11ea-91b7-0e26fed6b4f1.png)


![image](https://user-images.githubusercontent.com/50159788/68206140-eaf5c300-0006-11ea-8704-5ddae57daa58.png)

Is this a bug?

**Comment by haojin2** [comment]
@pedro-abundio-wang Seems like you're still using the pip package.
Are you using windows or linux?

**Comment by yzhliu** [comment]
@pedro-abundio-wang do you still have this issue using nightly build? if not can we close?

**Comment by talhaanwarch** [comment]
i am facing this issue on colab when I was using autogluon
```
!pip install -U pip
!pip install -U setuptools
!pip install -U wheel
!pip install -U "mxnet_cu110<2.0.0"
```
The model is trained on kaggle and inference is performed on colab, and I am getting the error
