### ISSUE TITLE
Documentation bug: format issue in the document of mxnet.gluon.contrib.estimator.GradientUpdateHandler

### ISSUE THREAD

**Issue by DNXie** [apache/mxnet#19773]
## Description

format issue in the document of `mxnet.gluon.contrib.estimator.GradientUpdateHandler`

## Link:
https://mxnet.apache.org/versions/1.7.0/api/python/docs/api/gluon/contrib/index.html#mxnet.gluon.contrib.estimator.GradientUpdateHandler

![image](https://user-images.githubusercontent.com/24580222/105425368-3c439f80-5c17-11eb-9122-561c50302891.png)

**Comment by GarrettDaniel** [comment]
I noticed this issue is still here, I'd love to help with it!  Just to clarify, the formatting issue is to remove the section in the red box, correct?

**Comment by TaoLv** [comment]
> I noticed this issue is still here, I'd love to help with it! Just to clarify, the formatting issue is to remove the section in the red box, correct?

It has been fixed on master branch via https://github.com/apache/mxnet/pull/20022. But seems the fix is not back ported to any release branch.

**Comment by GarrettDaniel** [comment]
Ok, good to know! In that case should this issue be closed?

**Comment by TaoLv** [comment]
Thanks. I'm closing it. If you are interesting in porting the fix to the release branch, feel free to open a PR for that.
